workflows:
  ios-workflow:
    name: iOS Workflow

    max_build_duration: 120

    environment:
      node: latest

      groups:
        - firebase

      vars:
        BUNDLE_ID: com.ibrahemherzallah.stellagold

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install Expo CLI
        script: |
          npm install -g expo-cli

      - name: Generate native ios project
        script: |
          npx expo prebuild --platform ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Create export options
        script: |
          rm -f /Users/builder/export_options.plist

          /usr/libexec/PlistBuddy -c "Add :method string app-store" /Users/builder/export_options.plist
          /usr/libexec/PlistBuddy -c "Add :signingStyle string automatic" /Users/builder/export_options.plist
          /usr/libexec/PlistBuddy -c "Add :uploadBitcode bool false" /Users/builder/export_options.plist
          /usr/libexec/PlistBuddy -c "Add :compileBitcode bool false" /Users/builder/export_options.plist

          plutil -lint /Users/builder/export_options.plist
          cat /Users/builder/export_options.plist

      - name: Show iOS files
        script: |
          ls ios
          find ios -name "*.xcworkspace"

      - name: Build IPA
        script: |
          cd ios
          xcodebuild -list

          xcode-project build-ipa \
            --workspace ./StellaGold.xcworkspace \
            --scheme StellaGold \
            --archive-flags="-allowProvisioningUpdates CODE_SIGN_STYLE=Automatic" \
            --export-options-plist /Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa